apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superagente.fullname" . }}-secrets
  namespace: {{ include "superagente.namespace" . }}
  labels:
    {{- include "superagente.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
