"""LLM output firewall: validates tool calls generated by the model.

Catches data exfiltration attempts, SSRF via tool calls, and oversized code execution.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass

from src.core.logger import get_logger

logger = get_logger(__name__)

_MAX_CODE_BLOCK_SIZE = int(os.getenv("LLM_FIREWALL_MAX_CODE_SIZE", "50000"))
_MAX_URL_LENGTH = 2048


@dataclass(frozen=True)
class FirewallDecision:
    allowed: bool
    reason: str = ""


def validate_tool_output(tool_data: dict) -> FirewallDecision:
    """Validates a parsed tool call from LLM output before execution."""
    action = tool_data.get("action", "")

    if action == "execute_code":
        code = tool_data.get("code", "")
        if len(code) > _MAX_CODE_BLOCK_SIZE:
            logger.warning("LLM firewall: code block too large (%d chars)", len(code))
            return FirewallDecision(
                allowed=False,
                reason=f"Bloque de código excede el límite ({len(code)} > {_MAX_CODE_BLOCK_SIZE})",
            )

        dangerous_patterns = [
            r"\bos\.system\s*\(",
            r"\bsubprocess\.",
            r"\beval\s*\(",
            r"\bexec\s*\(",
            r"\b__import__\s*\(",
            r"\bopen\s*\(['\"]\/etc",
            r"\brequests\.get\s*\(['\"]http",
        ]
        for pattern in dangerous_patterns:
            if re.search(pattern, code):
                logger.warning("LLM firewall: dangerous code pattern detected: %s", pattern)
                return FirewallDecision(
                    allowed=False,
                    reason=f"Patrón de código peligroso detectado.",
                )

    if action == "search_web":
        query = tool_data.get("query", "")
        if len(query) > _MAX_URL_LENGTH:
            return FirewallDecision(allowed=False, reason="Query de búsqueda demasiado larga.")

    url_fields = [tool_data.get("url", ""), tool_data.get("base_url", "")]
    for url in url_fields:
        if url:
            from src.security.url_validator import validate_url
            result = validate_url(url, context="llm_firewall_tool_call")
            if not result.safe:
                return FirewallDecision(allowed=False, reason=f"URL en tool call bloqueada: {result.reason}")

    return FirewallDecision(allowed=True)
